---
- name: bootstrapping and new user creation
  hosts: raiders
  gather_facts: no
  connection: ansible.builtin.ssh

  vars:
    newusers:
    - marian
    - belloq
    - willie
    - elsa

  tasks:
  - name: update apt with latest repo info
    ansible.builtin.raw: "apt update -y"
    become: yes

  - name: install py3 and pip3 with ansible raw
    ansible.builtin.raw: "apt install -y python3-pip"
    become: yes

  - name: create new group
    ansible.builtin.group:
      name: indymovies
      state: present
    become: yes

  - name: Add newusers to target hosts
    ansible.builtin.user:
      name: "{{ item|capitalize }}"        ## i added capitalized here,even though the origianl lab did not have it, this is on me to add capitalize
      state: present
      group: indymovies
    become: yes
    loop: "{{ newusers }}"

